---
title: "fl1"
format: html
editor: visual
---
#install packages
```{r}
install.packages(c("tidyverse", "readxl", "janitor", "here"))
install.packages(c("cars", "effectsize", "rstatix"))
install.packages("sjmisc")
install.packages("writexl")
```


#packages
```{r}
#| message: false
# general use
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(car) # levene test
library(effectsize) # assess effect size 
library(rstatix) # anova, kruskal wallis
library(sjmisc)
library(writexl)
```

#June FL1 Read Data - TEST
```{r}
fl1_june <- read_xlsx(path = here("data", "june 2026 firebreak, aidan copy 1.xlsx"),
                      sheet = "FL1")

fl1s_june <- read_xlsx(path = here("data", "june 2026 firebreak, aidan copy 1.xlsx"),
                      sheet = "FL1S")

fl1n_june <- read_xlsx(path = here("data", "june 2026 firebreak, aidan copy 1.xlsx"),
                      sheet = "FL1N")

```

#June FL1 Wrangling - TEST
```{r}
fl1_june_clean <- fl1_june %>% 
  slice(-81) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words 
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "central") %>% 
  drop_na(cover) #remove all species not observed

fl1s_june_clean <- fl1s_june %>% 
   drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "south") %>% 
  drop_na(cover) #remove all species not observed

fl1n_june_clean <- fl1n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "north") %>% 
  drop_na(cover) #remove all species not observed

fl1_full <- merge_df(fl1_june_clean, fl1s_june_clean, fl1n_june_clean) #merge all fl1 dfs
```



#June Data Read In
```{r}
#Staging Area 1
sa1_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA1")

sa1s_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA1S")

sa1n_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA1N")

#Flat 1
fl1_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL1")

fl1s_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL1S")

fl1n_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL1N")

#Slope 1
sl1_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL1")

sl1w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL1W")

sl1e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL1E")

#Staging Area 2
sa2_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA2")

sa2s_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA2S")

sa2n_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA2N")

#Flat 2
fl2_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL2")

fl2w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL2W")

fl2e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "FL2E")

#Slope 2
sl2_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL2")

sl2n_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL2N")

sl2s_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL2S")

#Staging Area 3
sa3_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA3")

sa3e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA3E")

sa3w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA3W")

#Flat 3
#fl3_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "FL3")

#fl3e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "FL3E")

#fl3w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "FL3W")

#Slope 3
sl3_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL3")

sl3w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL3W")

sl3e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SL3E")

#Staging Area 4
sa4_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA4")

sa4e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      sheet = "SA4E")

#no SA4N due to STIPA planting in January

#Staging Area 6
#sa6_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "SA6")

#sa6e_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "SA6E")

#sa6w_june <- read_xlsx(path = here("data", "FirebreakData2026_final.xlsx"),
                      #sheet = "SA6W")
```

#June Wrangling
```{r}
#Staging Area 1 Wrangling
sa1_june_clean <- sa1_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa1s_june_clean <- sa1s_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "south", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa1n_june_clean <- sa1n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "north", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa1_full <- merge_df(sa1_june_clean, sa1s_june_clean, sa1n_june_clean)

#Flat 1 Wrangling
fl1_june_clean <- fl1_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1s_june_clean <- fl1s_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "south", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1n_june_clean <- fl1n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "north", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1_full <- merge_df(fl1_june_clean, fl1s_june_clean, fl1n_june_clean)

#Slope 1 Wrangling
sl1_june_clean <- sl1_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1e_june_clean <- sl1e_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "east", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1w_june_clean <- sl1w_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "west", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1_full <- merge_df(sl1_june_clean, sl1e_june_clean, sl1w_june_clean)

#Staging Area 2 Wrangling
sa2_june_clean <- sa2_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "staging area", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa2s_june_clean <- sa2s_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "staging area", orientation = "south", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa2n_june_clean <- sa2n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "staging area", orientation = "north", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa2_full <- merge_df(sa2_june_clean, sa2s_june_clean, sa2n_june_clean)

#Flat 2 Wrangling
fl2_june_clean <- fl2_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2e_june_clean <- fl2e_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "east", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2w_june_clean <- fl2w_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "west", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2_full <- merge_df(fl2_june_clean, fl2e_june_clean, fl2w_june_clean)

#Slope 2 Wrangling
sl2_june_clean <- sl2_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2n_june_clean <- sl2n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "north", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2s_june_clean <- sl2s_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "south", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2_full <- merge_df(sl2_june_clean, sl2n_june_clean, sl2s_june_clean)

#Staging Area 3 Wrangling
sa3_june_clean <- sa3_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3e_june_clean <- sa3e_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "east", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3w_june_clean <- sa3w_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "west", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3_full <- merge_df(sa3_june_clean, sa3e_june_clean, sa3w_june_clean)

#Flat 3 Wrangling - not collected yet


#Slope 3 Wrangling
sl3_june_clean <- sl3_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3e_june_clean <- sl3e_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "east", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3w_june_clean <- sl3w_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "west", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3_full <- merge_df(sl3_june_clean, sl3e_june_clean, sl3w_june_clean)

#Staging Area 4 Wrangling
sa4_june_clean <- sa4_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 4, aspect = "staging area", orientation = "central", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa4e_june_clean <- sa4e_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 4, aspect = "staging area", orientation = "east", month = "June", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa4_full <- merge_df(sa4_june_clean, sa4e_june_clean)

#Staging Area 6 - not collected yet
```


#June Full Species List
```{r}
june <- merge_df(fl1_full, fl2_full, sa1_full, sa2_full, sa3_full, sa4_full, sl1_full, sl2_full, sl3_full)

all_june <- june %>%
  mutate(status = case_when(
    site == 1 & aspect == "slope" ~ "Slope 1",
    site == 1 & aspect == "flat" ~ "Flat 1",
    site == 1 & aspect == "staging area" ~ "Staging Area 1",
    site == 2 & aspect == "slope" ~ "Slope 2",
    site == 2 & aspect == "flat" ~ "Flat 2",
    site == 2 & aspect == "staging area" ~ "Staging Area 2",
    site == 3 & aspect == "slope" ~ "Slope 3",
    site == 3 & aspect == "staging area" ~ "Staging Area 3",
    site == 4 & aspect == "staging area" ~ "Staging Area 4",
    .default = "Other"))

species_list <- june %>% dplyr::select(species) %>% distinct()

write_xlsx(species_list, "species_list_june.xlsx")

species_class <- read_xlsx(path = here("data", "species_june_classified.xlsx"))
```

#Merge DFs (all june & classified species)
```{r}
all_june_classified <- merge(all_june, species_class, by = "species")
```

#June Plotting N/NN
```{r}
ggplot(all_june_classified) +
  aes(y = (as.numeric(as.character(cover))), x = status, color = class ) +
  geom_boxplot() +
  facet_wrap(~status, ncol = 3, scales = "free") +
  #geom_point(position=position_jitterdodge(
 #  jitter.width = 0,
 #  jitter.height = 0,
 #   seed = NULL),
  #          alpha = 0.3) +
  scale_color_manual(values = c("#e52e39", "#FFBF00", "#3271a5")) +
  labs(x = "Aspect",
       y = "Cover",
       color = "Cover Type") +
  theme_minimal()

#is there a correlation between native cover and nn or bareground?
```


#Nov Data Read In
```{r}
#Staging Area 1
sa1_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA1")

sa1s_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA1S")

sa1n_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA1N")

#Flat 1
fl1_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL1")

fl1s_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL1S")

fl1n_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL1N")

#Slope 1
sl1_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL1")

sl1w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL1W")

sl1e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL1E")

#Staging Area 2
#sa2_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      #sheet = "SA2")

#sa2s_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      #sheet = "SA2S")

#sa2n_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      #sheet = "SA2N")

#Flat 2
fl2_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL2")

fl2w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL2W")

fl2e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL2E")

#Slope 2
sl2_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL2")

sl2n_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL2N")

sl2s_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL2S")

#Staging Area 3
sa3_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA3")

sa3e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA3E")

sa3w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA3W")

#Flat 3
fl3_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL3")

fl3e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL3E")

fl3w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "FL3W")

#Slope 3
sl3_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL3")

sl3w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL3W")

sl3e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SL3E")

#Staging Area 4
sa4_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA4")

sa4e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA4E")

sa4n_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA4N")

#Staging Area 6
sa6_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA6")

sa6e_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA6E")

sa6w_nov <- read_xlsx(path = here("data", "FirebreakData_Nov2026.xlsx"),
                      sheet = "SA6W")
```

#Nov Wrangling
```{r}
#Staging Area 1 Wrangling
sa1_nov_clean <- sa1_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa1s_nov_clean <- sa1s_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "south", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  
  
sa1n_nov_clean <- sa1n_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "staging area", orientation = "north", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa1_full_nov <- merge_df(sa1_nov_clean, sa1s_nov_clean, sa1n_nov_clean)

#!!!!!!!!!!!!!!!!!!!!!!!!!!!! ADD MONTH & YEAR HERE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#Flat 1 Wrangling
fl1_nov_clean <- fl1_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1s_nov_clean <- fl1s_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "south", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1n_nov_clean <- fl1n_june %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "flat", orientation = "north", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl1_full_nov <- merge_df(fl1_nov_clean, fl1s_nov_clean, fl1n_nov_clean)

#Slope 1 Wrangling
sl1_nov_clean <- sl1_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1e_nov_clean <- sl1e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1w_nov_clean <- sl1w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 1, aspect = "slope", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl1_full_nov <- merge_df(sl1_nov_clean, sl1e_nov_clean, sl1w_nov_clean)

#Staging Area 2 Wrangling - lost datasheet

#Flat 2 Wrangling
fl2_nov_clean <- fl2_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2e_nov_clean <- fl2e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2w_nov_clean <- fl2w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "flat", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl2_full_nov <- merge_df(fl2_nov_clean, fl2e_nov_clean, fl2w_nov_clean)

#Slope 2 Wrangling
sl2_nov_clean <- sl2_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2n_nov_clean <- sl2n_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "north", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2s_nov_clean <- sl2s_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 2, aspect = "slope", orientation = "south", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl2_full_nov <- merge_df(sl2_nov_clean, sl2n_nov_clean, sl2s_nov_clean)

#Staging Area 3 Wrangling
sa3_nov_clean <- sa3_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3e_nov_clean <- sa3e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3w_nov_clean <- sa3w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "staging area", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa3_full_nov <- merge_df(sa3_nov_clean, sa3e_nov_clean, sa3w_nov_clean)

#Flat 3 Wrangling
fl3_nov_clean <- fl3_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "flat", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl3e_nov_clean <- fl3e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "flat", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl3w_nov_clean <- fl3w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "flat", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

fl3_full_nov <- merge_df(fl3_nov_clean, fl3e_nov_clean, fl3w_nov_clean)

#Slope 3 Wrangling
sl3_nov_clean <- sl3_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3e_nov_clean <- sl3e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3w_nov_clean <- sl3w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 3, aspect = "slope", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sl3_full_nov <- merge_df(sl3_nov_clean, sl3e_nov_clean, sl3w_nov_clean)

#Staging Area 4 Wrangling
sa4_nov_clean <- sa4_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 4, aspect = "staging area", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa4e_nov_clean <- sa4e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 4, aspect = "staging area", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa4n_nov_clean <- sa4n_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 4, aspect = "staging area", orientation = "north", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed

sa4_full_nov <- merge_df(sa4_nov_clean, sa4e_nov_clean, sa4n_nov_clean)

#Staging Area 6
sa6_nov_clean <- sa6_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 6, aspect = "staging area", orientation = "central", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa6e_nov_clean <- sa6e_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 6, aspect = "staging area", orientation = "east", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed  

sa6w_nov_clean <- sa6w_nov %>% 
  drop_na(Species) %>% # remove n/a row
  rotate_df() %>% 
  row_to_names(row_number = 1) %>% #name rows with values from row 1 (species)
  rownames_to_column() %>% 
  mutate(rowname = case_when(grepl("No.", rowname) ~ "Number",
                           grepl("Cov.", rowname) ~ "Cover")) %>% #rename values to regular words
  pivot_longer(cols = ACMAME:HIRINC,
              names_to = "species",
              values_to = "values") %>% #elongate df with species as values, not columns
  pivot_wider(names_from = "rowname",
              values_from = "values") %>% #create columns for number and cover
  clean_names() %>% 
  rename(strip = strip_no,
         quad = quad_no) %>% 
  mutate(site = 6, aspect = "staging area", orientation = "west", month = "November", year = "2026") %>% 
  drop_na(cover)  #remove all species not observed

sa6_full_nov <- merge_df(sa6_nov_clean, sa6e_nov_clean, sa6w_nov_clean)
```


#November Species List
```{r}
nov <- merge_df(fl1_full_nov, fl2_full_nov, fl3_full_nov, sa1_full_nov, sa6_full_nov, sa3_full_nov, sa4_full_nov, sl1_full_nov, sl2_full_nov, sl3_full_nov)

all_nov <- nov %>%
  mutate(status = case_when(
    site == 1 & aspect == "slope" ~ "Slope 1",
    site == 1 & aspect == "flat" ~ "Flat 1",
    site == 1 & aspect == "staging area" ~ "Staging Area 1",
    site == 2 & aspect == "slope" ~ "Slope 2",
    site == 2 & aspect == "flat" ~ "Flat 2",
    site == 6 & aspect == "staging area" ~ "Staging Area 6",
    site == 3 & aspect == "slope" ~ "Slope 3",
    site == 3 & aspect == "flat" ~ "Flat 3",
    site == 3 & aspect == "staging area" ~ "Staging Area 3",
    site == 4 & aspect == "staging area" ~ "Staging Area 4",
    .default = "Other"))

species_list_nov <- nov %>% dplyr::select(species) %>% distinct()

write_xlsx(species_list_nov, "species_list_nov.xlsx")

species_class <- read_xlsx(path = here("data", "species_list_nov_classified.xlsx"))

all_nov_classified <- merge(all_nov, species_class, by = "species")
```



#Comparison Nov/June
```{r}
all_all <- merge_df(all_nov_classified, all_june_classified) %>% 
   mutate(class = case_when(
    class == "native" ~ "Native",
    class == "non-native" ~ "Non-Native",
    class == "bare ground" ~ "Bare Ground")) %>% 
  dplyr::mutate(month = fct_relevel(month, "November", "June"),
                class = fct_relevel(class, "Native", "Non-Native", "Bare Ground"))

all_sumcover <- all_all %>% group_by(year, month, status, orientation, strip, quad, class) %>% summarise(sumcover = sum(as.numeric(as.character(cover))))
```




#Figures - Sum Cover
```{r}
#Figure Base
sa4_sumcover <- all_sumcover %>%  filter(status == "Staging Area 4") 

ggplot(sa4_sumcover) +
  aes(y = sumcover, x = class, color = class) +
  geom_boxplot() +
  facet_wrap(~month, scales = "fixed") +
  #geom_point(position=position_jitterdodge(
   #jitter.width = 0,
   #jitter.height = 0,
   # seed = NULL),
    #        alpha = 0.3) +
  scale_color_manual(values = c("#38A800", "#e52e39", "#888")) +
  labs(x = NULL,
       y = "Cover") +
  ggtitle("Staging Area 4") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "none")
```

